#!/bin/bash
 
NAME="codekitchen"                                        # Name of the application
VENV_DIR=/webapps/codekitchen/
DJANGODIR=/webapps/codekitchen/codekitchen/codekitchen                    # Django project directory
SOCKFILE=/webapps/codekitchen/run/gunicorn.sock           # we will communicate using this unix socket
USER=codekitchen                                          # the user to run as
GROUP=webapps                                     # the group to run as
NUM_WORKERS=3                                     # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=codekitchen.settings               # which settings file should Django use 
DJANGO_WSGI_MODULE=codekitchen.wsgi                       # WSGI module name
 
echo "Starting $NAME as `whoami`"
 
# Activate the virtual environment
cd $DJANGODIR
source /webapps/codekitchen/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH
 
# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR
 
# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec /webapps/codekitchen/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --log-level=debug \
  --bind=unix:$SOCKFILE

