from private_settings import (
    DEBUG,
    TEMPLATE_DEBUG,
    ALLOWED_HOSTS,
    ROOT_URL,
    AUTH_ROOT_URL,
    LOGIN_REDIRECT_URL,
    DATABASES,
    STATIC_URL,
    EMAIL_BACKEND,
    EMAIL_HOST,
    EMAIL_PORT,
    EMAIL_HOST_USER,
    EMAIL_HOST_PASSWORD,
    EMAIL_PREFIX,
    SESSION_COOKIE_DOMAIN,
        )

from shared_private import (
    SECRET_KEY,
        )

from shared_settings import (
    BASE_DIR,
    REPO_DIR,
    INSTALLED_APPS,
    MIDDLEWARE_CLASSES,
    ROOT_URLCONF,
    WSGI_APPLICATION,
    LANGUAGE_CODE,
    TIME_ZONE,
    USE_I18N,
    USE_L10N,
    USE_TZ,
    STATICFILES_DIRS,
    TEMPLATE_DIRS,
    TEMPLATE_CONTEXT_PROCESSORS,
    STATIC_ROOT,
    LOGGING,
        )
